CREATE TABLE "GCG_3723_MATCHING"(
 "BIRUNID" BIGINT,
 "SOCIAL_SECURITY_NO" CHAR(9),
 "FIRST_NAME" CHAR(30),
 "GROSSPAY" FLOAT,
 "EMPLOYEE_AMT" FLOAT,
 "COMPANY_AMT" FLOAT,
 "LOAN" FLOAT,
 "TOTLHRS" FLOAT);
