CREATE TABLE "GCG_3723_401K_AUDIT"(
 "BIRUNID" BIGINT,
 "EMPLOYEE" CHAR(5),
 "FIRST_NAME" CHAR(30),
 "LAST_NAME" CHAR(30),
 "GROSSPAY" FLOAT,
 "EMPLOYEE_AMT" FLOAT,
 "COMPANY_AMT" FLOAT,
 "LOAN" FLOAT,
 "PRINC" FLOAT,
 "INTEREST" FLOAT,
 "DATE_CHECK" DATE,
 "CHECK_NUM" CHAR(6),
 "SOCIAL_SECURITY_NO" CHAR(9));
