CREATE TABLE "GCG_3723_PENSION"(
 "BIRUNID" BIGINT,
 "SOCIAL_SECURITY_NO" CHAR(9),
 "EMPLOYEE" CHAR(5),
 "LAST_NAME" CHAR(30),
 "FIRST_NAME" CHAR(30),
 "MIDDLE_NAME" CHAR(1),
 "GROSSPAY" FLOAT,
 "BIRTHDATE" DATE,
 "DATE_HIRE" DATE,
 "DATE_TERMINATION" DATE,
 "TOTLHRS" FLOAT,
 "SEX" CHAR(1));
